### ISSUE TITLE
TeleportedMode parameterset for PT

### ISSUE THREAD

**Issue by Hussein-Mahfouz** [Hussein-Mahfouz/matsim-drt#10]
Do I need to remove TeleportedMode parameterset for pt in the config? By default it exists as shown below. If I understand correctly, it means pt is half the speed as car. Could this be why there is no pt in my output?

```xml
<parameterset type="teleportedModeParameters">
	<param name="beelineDistanceFactor" value="1.3" />
	<param name="mode" value="pt" />
	<param name="teleportedModeFreespeedFactor" value="2.0" />
	<param name="teleportedModeSpeed" value="null" />
</parameterset>
```

**Comment by balacmi** [comment]
Yes, you should remove it, if you want to use simulated pt from gtfs schedules. Then in the transit module in the config file you need to set useTransit to true
